name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Se déplacer dans le sous-dossier
        run: cd GeV5_refactor && pwd

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Installer dépendances
        run: |
          cd GeV5_refactor
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Tests
        run: |
          cd GeV5_refactor
          pytest || echo "Pas de tests ou erreurs non bloquantes"

      - name: Analyse sécurité Python
        run: |
          cd GeV5_refactor
          pip install bandit
          bandit -r .